name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: alish
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: mydb
        options: >-
          --health-cmd "pg_isready -U alish"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports: ["6379:6379"]

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: 🧪 Run tests
        env:
          DATABASE_URL: postgresql+asyncpg://alish:admin@localhost/mydb
          SECRET_KEY: supersecret
          CELERY_BROKER_URL: redis://localhost:6379/0
          CELERY_RESULT_BACKEND: redis://localhost:6379/0
        run: |
          pytest

      - name: 🐳 Build Docker image
        run: |
          docker build . -t myapp:latest
